project-code/app/models.py
from app import db

class Questions(db.Model):
    
    id = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.String(350), unique = True, nullable = False)
    option_a  = db.Column(db.String(100), nullable = False)
    option_b = db.Column(db.String(100), nullable = False)
    option_c = db.Column(db.String(100), nullable = False)
    option_d = db.Column(db.String(100), nullable = False)
    difficulty = db.Column(db.Enum('easy','medium','challenging'),name = 'difficulty', nullable = False)
    correct_answer = db.Column(db.String(100), nullable=False)
    

project-code/app/__init__.py
from flask import Flask
from config import Config
from app.db import db 

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)

    with app.app_context():
        from app.routes.main import main
        from app.routes.quiz import quiz_bp
        from app.routes.utils import utils 

        app.register_blueprint(main)
        app.register_blueprint(quiz_bp)
        app.register_blueprint(utils)

    return app

project-code/app/routes/main.py
from flask import Blueprint, render_template, session


main = Blueprint('main', __name__)

@main.route('/')
def index():
    session_keys = ['quiz_completed', 'score', 'current_index', 'question_ids', 'quiz_length', 'final_score']
    for key in session_keys:
        session.pop(key, None)
    
    return render_template('/home.html')

project-code/app/routes/quiz.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request
from app.models import Questions
import random
from app.utils.quiz_handler import QuizHandler

quiz_bp = Blueprint('quiz', __name__)

@quiz_bp.route('/quiz')
def start():
    quiz_handler = QuizHandler()
    session['quiz'] = quiz_handler.serialize()
    return redirect(url_for('quiz.questions', index=0))
    

@quiz_bp.route('/quiz/question/<int:index>')
def questions(index):
    if 'quiz' not in session:
        flash('Please start the quiz first.', 'warning')
        return redirect(url_for('quiz.start'))

    quiz_handler = QuizHandler.deserialize(session['quiz'])
    
    if quiz_handler.completed or index != quiz_handler.curr_index:
        return redirect(url_for('quiz.results'))
    
    question = quiz_handler.get_current_question()
    
    if question:
        return render_template('quiz.html', question=question, index=index)
    else:
        quiz_handler.curr_index += 1 
        session['quiz'] = quiz_handler.serialize() 
        return redirect(url_for('quiz.questions', index=quiz_handler.curr_index))

    
@quiz_bp.route('/submit_answer/<int:question_id>', methods=['POST'])
def submit_answer(question_id):
    selected_option = request.form.get('q_answer')
    
    quiz_data = session.get('quiz')
    if not quiz_data:
        flash("Quiz not started.", "warning")
        return redirect(url_for('quiz.start'))

    quiz_handler = QuizHandler.deserialize(quiz_data)

    # Check if an answer was submitted
    if not selected_option:
        flash('Please select an option.', 'warning')
        # Do not advance to the next question, just reload current question
        return redirect(url_for('quiz.questions', index=quiz_handler.curr_index))
    else:
        if quiz_handler.submit_answer(selected_option):
            flash('Correct!', 'success')
        else:
            flash('Incorrect answer.', 'info')
        # Only advance to the next question if an option was submitted
        quiz_handler.next_question()

    session['quiz'] = quiz_handler.serialize()
    
    if quiz_handler.completed:
        return redirect(url_for('quiz.results'))
    else:
        return redirect(url_for('quiz.questions', index=quiz_handler.curr_index))

@quiz_bp.route('/results')
def results():
    if 'quiz' not in session:
        flash('Quiz not started or session expired.', 'warning')
        return redirect(url_for('quiz.start'))
    
    quiz_handler = QuizHandler.deserialize(session['quiz'])
    
    if not quiz_handler.completed:
        flash('Quiz is not yet completed.', 'info')
        return redirect(url_for('quiz.questions', index=quiz_handler.curr_index))

    session.clear() 
    return render_template('results.html', final_score=quiz_handler.score, quiz_length=quiz_handler.get_quiz_length())

project-code/app/routes/utils.py
from flask import Blueprint, request, flash, redirect, url_for, session
from app import db
from app.models import Questions
from app.utils.handler import Handler 

utils = Blueprint('utils', __name__)


@utils.route('/upload', methods=['POST'])
def upload_file():
    
    if 'question_ids' in session and 'quiz_completed' not in session:
        flash('You cannot upload questions during an ongoing quiz.', 'error')
        return redirect(url_for('main.index'))
    
    if 'file' not in request.files:
        flash('Missing File Data', 'error')
        return redirect(url_for('/'))
    file = request.files['file']
    if file:
        if Questions.query.first():
            flash('The database already has questions. Starting the quiz with existing questions.', 'info')
            return redirect(url_for('quiz.start'))
        try:
            processed_q, erroneous_q = Handler.process_file(file)
            db.create_all()
            for question in processed_q:
                question = Questions(**question)
                db.session.add(question)
            db.session.commit()
            
            flash('Questions uploaded successfully', 'success')
            return redirect(url_for('quiz.start'))
        
        except Exception as e:
            db.session.rollback()
            flash(str(e), 'error')
            return redirect(url_for('main.index'))
        
    
    

project-code/app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
<div class="container-fluid">
    
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <img src="static\images\logo.png" alt="Logo" class = "logo">
                <h3>TLC's Quiz Web App</h3>
            </div>
            <div class="modal-body">
                <form action="/upload" method="post" enctype="multipart/form-data">
                    <div class="file-upload-form" id="file-upload" data-toggle="buttons">
                        <label class="element-animation1 btn btn-lg btn-primary btn-block">
                            <input id="file-upload-input" type="file" name="file" accept=".xlsx, .xls" style="display: none;">
                            <span id="choose-file-section">
                                <i class="fas fa-file-upload"></i> Upload file
                            </span>
                            <i id="excel-icon" class="fas fa-file-excel" style="display: none;"></i> <span id="file-name"></span>
                        </label>
                        <button type="submit" class="element-animation2 btn btn-lg btn-primary btn-block">
                            <i class="fas fa-cog"></i> Generate Quiz
                        </button>
                    </div>
                </form>
                <img src="/static/images/flask_logo.png" alt="Image" class="footer-image">
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>
</html>

project-code/app/templates/quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz Question</title>
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/quiz.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
<div class="container-fluid">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3>{{ question.question }}</h3>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('quiz.submit_answer', question_id=question.id) }}" method="post">
                    <div class="quiz" id="quiz" data-toggle="buttons">
                        <label class="element-animation1 btn btn-lg btn-primary btn-block">
                            <input type="radio" name="q_answer" value="a"> {{ question.option_a }}
                        </label>
                        <label class="element-animation2 btn btn-lg btn-primary btn-block">
                            <input type="radio" name="q_answer" value="b"> {{ question.option_b }}
                        </label>
                        <label class="element-animation3 btn btn-lg btn-primary btn-block">
                            <input type="radio" name="q_answer" value="c"> {{ question.option_c }}
                        </label>
                        <label class="element-animation4 btn btn-lg btn-primary btn-block">
                            <input type="radio" name="q_answer" value="d"> {{ question.option_d }}
                        </label>
                    </div>
                    <div class="modal-footer">
                        {% if last_question %}
                            <button type="submit" class="btn btn-success">Submit</button>
                        {% else %}
                            <button type="submit" class="btn btn-success">Next Question</button>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/quiz.js') }}"></script>
</body>
</html>

project-code/app/templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Quiz Result</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/results.css') }}">
<link href="https://fonts.googleapis.com/css2?family=Lexend:wght@400;700&display=swap" rel="stylesheet">
<script src="{{ url_for('static', filename='js/result.js') }}" defer></script>
</head>
<body>

<div class="modal">
  <div class="modal-header">
    <h2>Congratulations!</h2>
  </div>
  <div class="modal-body">
    <div class="score">Your quiz score is: <span id="finalScore">{{ final_score }}</span> out of <span id="quizLength">{{ quiz_length }}</span></div>
    <div class="circle-progress-container"></div>
    <div class="message">You've completed the quiz.<br>Click on Finish to redirect back to the home page.</div>
    <button class="button" onclick="window.location.href='/quiz'">Retake</button>
    <button class="button" onclick="window.location.href='/'">Finish</button>
  </div>
</div>

</body>
</html>